### ISSUE TITLE
Add jest test

### ISSUE THREAD

**Issue by eatplaynap** [eatplaynap/shadone#148]
## Links
- [RailsのVue.jsをWebpackerとJestでテストする（翻訳）｜TechRacho by BPS株式会社](https://techracho.bpsinc.jp/hachi8833/2018_03_26/53865)

## Tasks
- [x] Install Jest
- [x] Add test script 
- [x] Define where to put tests
- [x] Rescue babel
- [x] Install vue-jest
